version: '3.8'

services:
  olatcg-frontend:
    build:
      context: .
    container_name: olatcg-frontend
    ports:
      - "3030:3000"
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"

networks:
  olatcg-bridge:
    name: olatcg-bridge
    external: true