version: '3.8'

services:
  olatcg-frontend:
    image: luizmiguelvb/olatcg-frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:delegated"
      - "/usr/src/app/node_modules/"

networks:
  olatcg-bridge:
    name: olatcg-bridge
    external: true