const actionTypes = {

    // STEP CHANGE CONDITIONS
    SET_NEXT_CONDITION: 'SET_NEXT_CONDITION',
    SET_PREVIOUS_CONDITION: 'SET_PREVIOUS_CONDITION',
    RETURN_TO_STEP_CHANGE_CONDITIONS_INITIAL_STATE: 'RETURN_TO_STEP_CHANGE_CONDITIONS_INITIAL_STATE',

    // STEP FORM
    ADD_STEP_FORM_FIELD: 'ADD_STEP_FORM_FIELD',
    SET_STEP_FORM: 'SET_STEP_FORM',
    UPDATE_STEP_FORM: 'UPDATE_STEP_FORM',
    RETURN_TO_STEP_FORM_INITIAL_STATE: 'RETURN_TO_STEP_FORM_INITIAL_STATE',

    // STEP RESPONSE
    SET_STEP_RESPONSE: 'SET_STEP_RESPONSE',
    RETURN_STEP_RESPONSE_TO_INITIAL_STATE: 'RETURN_STEP_RESPONSE_TO_INITIAL_STATE',

    // STEP ACTUAL POSITION
    SET_STEP_ACTUAL_POSITION: 'SET_STEP_ACTUAL_POSITION',
};

export { actionTypes }